Hw08 is completed
avbru/homeworks pull request #11
Opened 2020-06-20 14:52 UTC by avbru

## Домашнее задание №8 «Утилита envdir» 

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-06-22 09:06 UTC, kulti requested changes
Александр, добрый день.

В коде не выполняется одно из условий задания:
- если файл полностью пустой (длина - 0 байт), то envdir удаляет переменную окружения с именем S.

Для тестирования этого случая посмотрите на метод os.LookupEnv.

2020-06-22 09:06 UTC, kulti commented on hw08_envdir_tool/env_reader.go
> +			continue
Почему тут не возвращается ошибка? Если имя файла некорректное, думаю, стоит сообщить об этом пользователю.

2020-06-22 09:06 UTC, kulti commented on hw08_envdir_tool/env_reader.go
> +			continue
Почему тут не возвращается ошибка?

2020-06-22 10:18 UTC, avbru commented on hw08_envdir_tool/env_reader.go
> +			continue
Ошибок в цикле может быть несколько (например кто то удалил пару файлов в момент исполнения). На мой взгляд такое поведение не является ошибкой с точки зрения логики выполнения программы.
Как вариант предлагаю залогировать проблему на месте. fmt.Printf("%s\n",err)
Или "обогощать" и возвращать одну длинную ошибку?

2020-06-22 10:23 UTC, avbru commented on hw08_envdir_tool/env_reader.go
> +			continue
Как и в пункте ниже, достаточно будет залогировать на месте?

2020-06-22 11:23 UTC, kulti commented on hw08_envdir_tool/env_reader.go
> +			continue
Я склоняюсь к тому, что это критичная ошибка. Мы пишем программы для пользователей. В данном случае, пользователь человек, и ему важно понимать, что происходит.

Рассмотрим пример:
- Пользователь запускается программу на некорректной директории с env-файлами.
- Что-то отработает, скорее всего не так, как он ожидал. Не факт, что он это заметит.
- Не сказать ему об этом - совсем плохо.
- Написать просто в лог - тоже так себе вариант. Не понятно, как он отличит вывод envdir от вывода той программы, которую он запустил.

Поэтому, считаю, что лучше вообще не запускать программу пользователя, если envdir не смог обработать файлы с переменным окружения.

2020-06-23 09:33 UTC, kulti approved these changes

2020-06-23 09:34 UTC, kulti commented
ДЗ принято - 10/10.

2020-06-23 09:48 UTC, merged