Hw11 telnet client
avbru/homeworks pull request #12
Opened 2020-06-20 18:36 UTC by avbru

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-06-22 08:56 UTC, kulti requested changes
Александр, добрый день.

В ПР попали изменения для  hw08_envdir_tool. Почистите, пожалуйста, от лишних коммитов. После этого готов принять на 7/10:
4 - за зеленый пайплайн
2 - за чистоту и понятность кода
1 - за тест случая, когда в NewTelnetClient передается невалидное значение address (остальные новые тесты ничего не добавляют, т.к. существующий тест уже все это проверил).

Если хотите больше баллов, то нужно добавить тесты на новые сценарии (разрыв соединения, пользователь нажал ctrl+c, может, еще что-то придумаете).

2020-06-22 08:56 UTC, kulti commented on hw11_telnet_client/telnet.go
> +func passData(in io.Reader, out io.Writer) error {
В стандартных пакетах уже есть подобная функция - io.Copy.

2020-08-18 10:51 UTC, avbru commented on hw11_telnet_client/telnet.go
> +func passData(in io.Reader, out io.Writer) error {
пробовал через io.Copy, тесты проходят, но если руками пробовать то работает нестабильно: "пропускает" нажатия клавиш ctrl-C/D

2020-08-21 17:39 UTC, kulti commented on hw11_telnet_client/telnet.go
> +func passData(in io.Reader, out io.Writer) error {
Да, действительно. Возможно, из-за оптимизации ReadFrom.

2020-08-21 17:50 UTC, kulti commented on hw11_telnet_client/workers_test.go
> +func TestLostConnection(t *testing.T) {
В этом тесте не очень хорошо, что он использует time.Sleep. Тесты на слипах всегда нестабильные, либо неоправданно медленные.

Так же лучше тестировать поведение публичного интерфейса, чтобы спокойно изменять внутренности (блэкбокс тестирования). На будущее предлагаю присмотреться к следующему паттерну для подобных случаев.

Вместо приватного метода `go listen(...)` протестировать публичный:
```
	recvErrCh := make(chan error)
	go func() {
		recvErrCh <- tc.Receive()
	}()
```

Тодга без всяких пайпов и слипов можно закрывать только tc: `require.NoError(t, tc.Close())`.

Остается только дождаться ошибки:
```
	var recvErr error
	require.Eventually(t, func() bool {
		select {
		case recvErr = <-recvErrCh:
			return true
		default:
			return false
		}
	}, time.Second, 100*time.Millisecond)

	require.Error(t, recvErr)
```

Далее можно проверить ошибку, что она именно та, что ожидалась.

2020-08-21 17:52 UTC, kulti approved these changes
Классно, что нашли время вернуться и доделать ДЗ. Получилсь хорошие тесты на сложные случаи. Оставил предложение, как можно по другому подходить к таким тестам, чтобы они были стабильнее и безопаснее.

ДЗ принято - 10 из 10.

2020-08-24 06:54 UTC, merged