HW2 is completed
avbru/homeworks pull request #3
Opened 2020-03-13 18:00 UTC by avbru

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-03-15 10:49 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/92261/6026/

Здравствуйте!

Спасибо за работу.
В целом решение хорошее.
* Строка, начинающаяся с цифры - невалидная.
* Еще бы парочку позитивных и негативных тестов.


Давайте подправим замечания и оценю.

2020-03-15 10:49 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +	"testing"
Предыдущий вариант сортировки импортов был более правильный в соответствии с 
https://github.com/golang/go/wiki/CodeReviewComments#imports

2020-03-15 10:49 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +	//t.Skip() // Remove if task with asterisk completed
Неактуальный код удаляем

2020-03-15 10:49 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +	//t.Skip() // Remove if task with asterisk completed
Неактуальный код удаляем

2020-03-15 10:49 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			input:    "4u",
Это же невалидная строка?

2020-03-15 10:49 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	if s == "" {
Нужна ли эта проверка? :)

2020-03-15 10:49 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	builder := strings.Builder{}
Предпочтительнее
```
var builder strings.Builder
```

2020-03-15 10:49 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	for r, _, err := reader.ReadRune(); err != io.EOF; r, _, err = reader.ReadRune() {
Цикл `for range` как раз проходится по рунам строки

2020-03-15 11:08 UTC, avbru commented on hw02_unpack_string/unpack_test.go
> +			input:    "4u",
В описании ДЗ, такой случай не описан. Добавил, так сказать, от себя.

2020-03-15 11:14 UTC, avbru commented on hw02_unpack_string/unpack.go
> +	if s == "" {
Это типа return early паттерн. Избежим аллокации нескольких переменных далее по коду в случае пустой строки. Алгоритму конечно не нужна...

2020-03-15 11:19 UTC, avbru commented on hw02_unpack_string/unpack.go
> +	for r, _, err := reader.ReadRune(); err != io.EOF; r, _, err = reader.ReadRune() {
Да. Только прочитать строку вперед на 1 руну не получится... Я пробовал так, на мой взгляд, код получался сложнее.

2020-03-16 14:31 UTC, Antonboom approved these changes
Принято
10 / 10

2020-03-17 16:58 UTC, merged